-- MySQL Script generated by MySQL Workbench
-- Wed Sep 11 10:55:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sportlib
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sportlib` ;

-- -----------------------------------------------------
-- Schema sportlib
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sportlib` DEFAULT CHARACTER SET utf8 ;
USE `sportlib` ;

-- -----------------------------------------------------
-- Table `sportlib`.`t_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportlib`.`t_place` ;

CREATE TABLE IF NOT EXISTS `sportlib`.`t_place` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `place` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `zip_code` VARCHAR(5) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `date_place` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportlib`.`t_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportlib`.`t_activity` ;

CREATE TABLE IF NOT EXISTS `sportlib`.`t_activity` (
  `id` BIGINT NOT NULL,
  `activity` VARCHAR(255) NOT NULL,
  `day` VARCHAR(10) NOT NULL,
  `startTime` TIME NOT NULL,
  `endTime` TIME NOT NULL,
  `date_activity` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportlib`.`t_place_has_t_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportlib`.`t_place_has_t_activity` ;

CREATE TABLE IF NOT EXISTS `sportlib`.`t_place_has_t_activity` (
  `t_place_id` BIGINT NOT NULL,
  `t_activity_id` BIGINT NOT NULL,
  PRIMARY KEY (`t_place_id`, `t_activity_id`),
  INDEX `fk_t_place_has_t_activity_t_activity1_idx` (`t_activity_id` ASC),
  INDEX `fk_t_place_has_t_activity_t_place_idx` (`t_place_id` ASC),
  CONSTRAINT `fk_t_place_has_t_activity_t_place`
    FOREIGN KEY (`t_place_id`)
    REFERENCES `mydb`.`t_place` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_place_has_t_activity_t_activity1`
    FOREIGN KEY (`t_activity_id`)
    REFERENCES `mydb`.`t_activity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
